source 'http://rubygems.org'

gem 'rspec', '3.1.0'
gem 'cucumber', '1.3.17'
gem 'test-factory', '0.5.3'
gem 'watir-webdriver', '0.6.10'
gem 'headless'
gem 'kuality-kfs'#, :git => 'https://CU-CommunityApps@github.com/CU-CommunityApps/kuality-kfs.git'
gem 'parallel_tests'
gem 'mechanize'
gem 'xml-simple'
gem 'syntax'