source 'http://rubygems.org'

gem 'rspec', '2.14.1'
gem 'cucumber', '1.3.14'
gem 'test-factory', '0.4.6'
gem 'watir-webdriver', '0.6.8'
gem 'headless'
gem 'kuality-kfs'#, :git => 'https://CU-CommunityApps@github.com/CU-CommunityApps/kuality-kfs.git'
gem 'parallel_tests'
gem 'mechanize'
gem 'xml-simple'
